# Generated by Django 6.0.7 on 2026-08-02 15:28

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kliens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kliens_azonosito', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nev', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('vallalat', models.CharField(blank=True, max_length=255, null=True)),
                ('letrehozva', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SzakmaIrany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255, unique=True)),
                ('leiras', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Konzultans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konzultans_azonosito', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nev', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('munka_kezdes', models.TimeField(default=datetime.time(9, 0))),
                ('munka_befejezes', models.TimeField(default=datetime.time(17, 0))),
                ('aktiv', models.BooleanField(default=True)),
                ('szakirany', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='konzultansok', to='booking.szakmairany')),
            ],
        ),
        migrations.CreateModel(
            name='Idopontok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idopont_azonosito', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kezdes', models.DateTimeField()),
                ('vege', models.DateTimeField()),
                ('statusz', models.CharField(choices=[('FÜGGŐ', 'Függő'), ('IGAZOLT', 'Igazolt'), ('VISSZAVONT', 'Visszavont')], default='CONFIRMED', max_length=20)),
                ('letrehozva', models.DateTimeField(auto_now_add=True)),
                ('kliens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idopontok', to='booking.kliens')),
                ('konzultans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idopontok', to='booking.konzultans')),
                ('szakirany', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.szakmairany')),
            ],
        ),
    ]
